Updated dashboard.html with wishlist
MathiasReker/WishShare pull request #56
Opened 2021-11-04 14:52 UTC by Andreassim

Added new functionality to WishLisControler.
Here we can now add a new wishlist for a loggedin user.
Moved dashboard in here

WishlistRepository updated wist a method for retrieve all wishlists for a given user.

Wishlist service updated to have the update from repository

Nice fronted :))))

What kind of change does this PR introduce?

- [ ] `bug-fix`
- [x] `new-feature`
- [x] `enhancement`

2021-11-04 21:15 UTC, MathiasReker requested changes

2021-11-04 21:15 UTC, MathiasReker commented on src/main/java/com/group6/wishshare/web/WishlistController.java
> +import com.group6.wishshare.domain.model.User;
Use a service in front of the model

2021-11-04 21:15 UTC, MathiasReker commented on src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
> +    PreparedStatement prep;
Can we use `ps` everywhere?

2021-11-04 21:18 UTC, MathiasReker commented on src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
> +    PreparedStatement prep;
and move the line inside the try block :)

2021-11-05 07:58 UTC, Andreassim commented on src/main/java/com/group6/wishshare/web/WishlistController.java
> +import com.group6.wishshare.domain.model.User;
we need a userservice class for this then. FrontController does the same.

Not fixing this in this PR

2021-11-05 08:00 UTC, Jarkyman approved these changes

2021-11-05 08:05 UTC, Andreassim commented on src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
> +    PreparedStatement prep;
fixed

2021-11-05 08:37 UTC, merged