wish controller and some ui
MathiasReker/WishShare pull request #58
Opened 2021-11-04 16:55 UTC by Moshizzl3

What kind of change does this PR introduce?

- [ ] `bug-fix`
- [ ] `new-feature`
- [x ] `enhancement`

2021-11-04 21:08 UTC, MathiasReker requested changes
Cool! Just a few comments.

2021-11-04 21:08 UTC, MathiasReker commented on src/main/resources/templates/createwish.html
> +    <meta charset="UTF-8">
```suggestion
```

2021-11-04 21:08 UTC, MathiasReker commented on src/main/resources/templates/createwish.html
> +<h1>Wish</h1>
Move to inside section

2021-11-04 21:08 UTC, MathiasReker commented on src/main/resources/templates/index.html
> +<a href="createwish">Create wish</a>
use kebab case for hyperlinks

2021-11-04 21:08 UTC, MathiasReker commented on src/main/java/com/group6/wishshare/web/WishController.java
> +import com.group6.wishshare.domain.model.Wish;
use a service between the controller and the model :-)

2021-11-04 21:08 UTC, MathiasReker commented on src/main/resources/static/css/soft-ui-dashboard.css
> +  width: 33%;
Don't edit the compiled CSS :) Why is this needed?

2021-11-04 21:08 UTC, MathiasReker commented on src/main/java/com/group6/wishshare/web/WishController.java
> +  @PostMapping("/new-wish")
Looks good! :)

2021-11-04 21:49 UTC, MathiasReker commented on src/main/resources/templates/createwish.html
> +<h1>Wish</h1>
Wrap the h1 tag and the section inside a article tag: https://css-tricks.com/how-to-section-your-html/

2021-11-05 08:02 UTC, Jarkyman approved these changes

2021-11-05 08:36 UTC, merged